### ISSUE TITLE
coverage 4 compatibility

### ISSUE THREAD

**Issue by tarpas** [tarpas/pytest-testmon#10]

**Comment by blueyed** [comment]
What needs to be done for this?

**Comment by tarpas** [comment]
I"m not at the computer. If you have a look at  3.7-4.0 coveragepy diff
around the save_data method you'll see that it changed. So the api and one
internal method will have to be used in different manner.

**Comment by blueyed** [comment]
So it does not seem like it's that much after all?

Would be nice then to have both coverage 3 and 4 in the Travis matrix then, once this gets addressed.

**Comment by tarpas** [comment]
@blueyed Do you think anybody will need coverage 3 support? I have a pytest_testmon v0.8.0 imminent which replaces support of coverage 3 with coverage 4. Pip seems to upgrade coverage nicely on upgrade of testmon

**Comment by blueyed** [comment]
@tarpas 
For me only testmon was holding it back.
I think it's fine to only support coverage 4 from 0.8 forward.

**Comment by tarpas** [comment]
Closed with v0.8.0

**Comment by blueyed** [comment]
Awesome, thanks!
