### ISSUE TITLE
Configure location of `.testmondata`

### ISSUE THREAD

**Issue by cleder** [tarpas/pytest-testmon#116]
When I run `py.test --testmon` I get the below error.
I suspect this is because the directory is mounted via NFS in my vagrant box.
Could the location of the db be made configurable?

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/_pytest/main.py", line 174, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/_pytest/config/__init__.py", line 588, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/pluggy/__init__.py", line 628, in call_historic
INTERNALERROR>     res = self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/testmon/pytest_testmon.py", line 122, in pytest_configure
INTERNALERROR>     init_testmon_data(config)
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/testmon/pytest_testmon.py", line 100, in init_testmon_data
INTERNALERROR>     variant=variant)
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/testmon/testmon_core.py", line 95, in __init__
INTERNALERROR>     self.init_connection()
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/testmon/testmon_core.py", line 113, in init_connection
INTERNALERROR>     self._check_data_version()
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/testmon/testmon_core.py", line 120, in _check_data_version
INTERNALERROR>     stored_data_version = self._fetch_attribute('__data_version', default=None, variant='default')
INTERNALERROR>   File "/home/vagrant/cms/venv/lib/python2.7/site-packages/testmon/testmon_core.py", line 133, in _fetch_attribute
INTERNALERROR>     [(variant if variant else self.variant) + ':' + attribute])
INTERNALERROR> OperationalError: disk I/O error
```

**Comment by tarpas** [comment]
so what would be your actual value for the setting?

**Comment by tarpas** [comment]
https://docs.pytest.org/en/latest/customize.html states that rootdir of pytest:
"Is used by plugins as a stable location to store project/test run specific information; for example, the internal cache plugin creates a .pytest_cache subdirectory in rootdir to store its cross-test run state."

Maybe you should reconfigure that if you need it?

**Comment by blueyed** [comment]
1. the error is a bit weird - it appears to happen when executing the `SELECT`: https://github.com/tarpas/pytest-testmon/blob/3dd6e8c8ca035f828cedb906f451b6418d71b510/testmon/testmon_core.py#L132-L133 - that could at least maybe produce a better error message.  Can the file be opened with e.g. `sqlite3` or `sqlitebrowser`?

2. you also use the `TESTMON_DATAFILE` environment variable to specify another location.

@tarpas 
I do not think configuring `rootdir` is a good advice, since this is more considered to be the project root really (for config files etc).
testmon should maybe use pytest's `cache_dir` setting instead for the default (which then can be re-configured by users).

**Comment by tarpas** [comment]
It's possible to place and name the file via TESTMON_DATAFILE environment variable.

**Comment by michealroberts** [comment]
@tarpas Hey there, thanks for this great tool. Apologies to bungie onto an existing closed issue, I couldn't find a discussions section for this repository and this was the most relevant issue to tack onto. 

This is more of a question ... but should we commit or not commit .testmondata to source control? I can't reference if we should or shouldn't do this ...
