### ISSUE TITLE
crash with non utf-8 encoding .py files

### ISSUE THREAD

**Issue by tarpas** [tarpas/pytest-testmon#14]
Eg.
lib/python3.4/site-packages/dateutil/parser.py
is supposedly # -_\- coding:iso-8859-1 -_\- 
testmon crashes 
with:
 File "/Users/tibor/tmonworkspace/testmon/testmon/process_code.py", line 47, in **init**
INTERNALERROR>     source_code = f.read()
INTERNALERROR>   File "/Users/tibor/tmonworkspace/warehouse/.tox/py34/bin/../lib/python3.4/codecs.py", line 319, in decode
INTERNALERROR>     (result, consumed) = self._buffer_decode(data, self.errors, final)

**Comment by tarpas** [comment]
@webknjaz the new release v0.9.7 should fix the problem with encoding, please test.

**Comment by webknjaz** [comment]
@tarpas Thanks! It works now :)

https://ci.appveyor.com/project/CherryPy/cheroot/build/169
https://ci.appveyor.com/project/CherryPy/cheroot/build/170
