### ISSUE TITLE
[docs] Where's `--testmon-off`?

### ISSUE THREAD

**Issue by webknjaz** [tarpas/pytest-testmon#146]
I had to visually/manually compare https://testmon.org/v0.9.x.html and https://testmon.org/ to guess that it's been renamed to `--no-testmon`.

https://testmon.org/new-in-testmon-100.html doesn't mention such changes but I think it should.

**Comment by tarpas** [comment]
Sviatoslav, thanks for the suggestion. I included it in section "Renames": https://testmon.org/new-in-testmon-100.html
