### ISSUE TITLE
Tests were removing are this project appreciate contributing?

### ISSUE THREAD

**Issue by tbicr** [tarpas/pytest-testmon#147]
I see significant changes with 1.0 release that really cool. But I a bit confusing with removed tests. Are they are just moved to other place? Otherwise how you can check that future changes don't break something?

**Comment by raboof** [comment]
I noticed the tests are available in the PyPI package (https://pypi.org/project/pytest-testmon/#files), so I assume they have been moved rather than removed, but I'm also confused where.

**Comment by tarpas** [comment]
This has been fixed with the latest commits and release.
