### ISSUE TITLE
What's v0.9.19?

### ISSUE THREAD

**Issue by webknjaz** [tarpas/pytest-testmon#149]
I noticed that it's distributed via PyPI but there's no mentions of this version in the changelog, nor a Git tag on GitHub. This probably needs to be documented and the commit should be tagged.

**Comment by tarpas** [comment]
apparently 9ad5ba296790fd8160ac22250febff01b22f7f0e is v0.9.19. There were no changes in the code, only on PYPI description.

**Comment by webknjaz** [comment]
Still, it may be confusing if there's no mention of this anywhere :)

**Comment by Matlino** [comment]
I added a missing tag.
