### ISSUE TITLE
should we commit .testmondata to version control?

### ISSUE THREAD

**Issue by hatemhosny** [tarpas/pytest-testmon#152]
I am new to testmon. This is a question about best practice regarding commiting `.testmondata` to version control. 

advantages I can think of include:
- ability to share the file thus a team member does not have to rerun the passing tests of other members
- switching branches would also switch to the relevant file

disadvantages:
- having to commit a generated file
- we run tests as pre-push hook. This will create a new file, messing the git history. We should then disable testmon in this run, and thus the push will take much longer time.

do you have any guidance for that?

thank you

**Comment by tarpas** [comment]
Unfortunately that doesn't seem to the right strategy. .testmondata is a binary file which would cause 2 problems:
1. conflicts on merges
2. going against the delta storage compression (although I didn't test this)
I don't have a good solution for this at the moment, I'm afraid.

**Comment by zevisert** [comment]
Apologies for waking an issue that was closed 4 years ago, but it still seems like the correct place for this discussion. 

What have people been doing? Would git LFS be a good solution for this file?

**Comment by tarpas** [comment]
I have worked on a client-server solution. I might make the server open-source/public in the coming months.

**Comment by udhayprakash** [comment]
I stored the testmon data in a separate branch that branch has only the testimony data file. Nothing else, in the lines of gh-pages. Update that branch only when main branch build ran. Use it in PR branches . I don't have concurrent mani branch builds.
