### ISSUE TITLE
Cython support

### ISSUE THREAD

**Issue by bergkvist** [tarpas/pytest-testmon#155]
It would be nice if this would somehow work for .pyx/.pxd files too. (Cython files)

**Comment by tarpas** [comment]
Cython is translated into C. Although it's not unthinkable someday coverage tracking/tracing will work across runtimes and different programming languages and there  will be a software product which would use the information for smart test selection at this point this is out of scope of pytest-testmon. Sorry :/.

**Comment by bergkvist** [comment]
I don't think you'd need to use coverage analysis for the generated C code to support this. pytest-testmon is already using coverage.py, right? Check out this:
http://blog.behnel.de/posts/coverage-analysis-for-cython-modules.html

pytest is already smart enough not to rebuild a .pyx-file unless it has changed. I guess a solution could be to just rerun every test that depends on a .pyx file whenever the file changes. This would be better than nothing.
