### ISSUE TITLE
Disable AppVeyor integration

### ISSUE THREAD

**Issue by hugovk** [tarpas/pytest-testmon#157]
All PRs are failing (eg. https://github.com/tarpas/pytest-testmon/pull/156) because AppVeyor is failing.

But there's no `.appveyor.yml` or `appveyor.yml` CI config to run tests.

Please could you disable the integration?

**Comment by tarpas** [comment]
I deleted a webhook to appveyor, let's see if it's correct when a new PR appears. Thanks.
