### ISSUE TITLE
Tests shipped with 1.0.3 are for a newer pytest-testmon

### ISSUE THREAD

**Issue by raboof** [tarpas/pytest-testmon#158]
The tests that are shipped with the version 1.0.3 PyPI package expect the `filenames_fingerprints` object to contain the additional `sum(failed)` field that was added in the commit right after the v1.0.3 tag, cfb7c2ded825c3d10843703023fdf02b7f8112cc

**Comment by tarpas** [comment]
Tests were not published yet via Github. I need to work on them a little
more and then I'll push them.

**Comment by tarpas** [comment]
I think this should be fixed now :)

**Comment by raboof** [comment]
Confirmed tests from PyPI seem to succeed now!
