### ISSUE TITLE
Question: pytest parametrization

### ISSUE THREAD

**Issue by cgebbe** [tarpas/pytest-testmon#162]
Not an issue, rather a quick question, which might also interesting to other people (and haven't find the answer on the homepage)

Our codebase makes heavy use of
- test parametrization via @pytest.mark.parametrize(...)
- fixture parametrization via @pytest.fixture(param=...)

In case a source code change only affects one of the parameters, would pytest-testmon run only the affected parameter or ALL parameters?

**Comment by tarpas** [comment]
All parameters unfortunately.
