### ISSUE TITLE
Support for vanilla unittest

### ISSUE THREAD

**Issue by m-aciek** [tarpas/pytest-testmon#163]
Would you consider supporting vanilla unittest from Python standard library? Is it much work in your opinion to extract an abstraction layer above of Pytest, e.g. if some volunteer would be about to work on it?

The project looks very promising, thank you for sharing it!

**Comment by m-aciek** [comment]
I learned that https://github.com/man-group/partialtesting may support that, but it requires some manual job to use it.

**Comment by tarpas** [comment]
Unfortunately I don't have any plans to do that. Reliable integration between coverage and pytest is more effort than anything else in pytest-testmon. I'll concentrate on improving testmon for pytest.. 

Why can't you switch the runner to pytest without changing the suite? (Honestly curious, not trying to be difficult)

**Comment by m-aciek** [comment]
I see. I can use Pytest, I was just wondering if it would be possible to have Testmon functionality without adding Pytest as a new dependency to my development stack.
