### ISSUE TITLE
Safety report for coverage < 6.0b1

### ISSUE THREAD

**Issue by theoden-dd** [tarpas/pytest-testmon#168]
For security reasons please update the plugin to be compatible with coverage ^6.0.

The current limitation for coverage `<6` makes it impossible to satisfy the safety requirement which is cited below.

Since the [august update](https://github.com/pyupio/safety-db/commit/3fc2a370bfab2c052a069811f65ba4aa3adf30d6#diff-3c561b12084d50ebca9e164979f7df4921085ae29a71bf4e4f4ee1c5f14ae9b5R711) safety reports the following:
```
+============================+===========+==========================+==========+
| coverage                   | 5.3       | <6.0b1                   | 41002    |
+==============================================================================+
| Coverage 6.0b1 starts to use a modern hash algorithm (sha256) when           |
| fingerprinting for high-security environments.                               |
+==============================================================================+
```

**Comment by tarpas** [comment]
Compatibility with coverage 6+ has been released with pytest-testmon v1.1.2 .
