### ISSUE TITLE
Enhancement idea: Add feature to use testmon with selected markers (pytest -m)

### ISSUE THREAD

**Issue by hnrhonkala88** [tarpas/pytest-testmon#173]
I can see that pytest-testmon is not currently supporting the scenario where user wants to select specific markers for the tests to run.
`testmon: selection automatically deactivated because -m was used, environment: default`

Anyway for our usage this would be a clear benefit to have this kind of feature in place.

We have different test sets for specific purposes and currently handling test selections with our own in-house solution. Anyway this tool seems to be quite handy and useful to handle the different kind of selection scenarios, except it does not activate the feature support while running tests with markers.

Do you think it would be possible to develop this kind of feature to this plugin? I would imagine there are also others that would be interested about such feature

**Comment by tarpas** [comment]
Hi Henri. Thanks for the suggestion!
I had the same idea last time when I was redesigning the command line options but something stopped me from implementing it. I thought it would be too confusing. Now, however I think it would be a good idea.

I'll formulate the enhancement request more formally later. As for implementation, no promises, but specifying what should be done is a good start.

**Comment by tarpas** [comment]
@hnrhonkala88 Henri, I think your scenario is fully supported with --testmon-forceselect switch (release long ago). If not let me know and let's reopen this ticket.

**Comment by hnrhonkala88** [comment]
> @hnrhonkala88 Henri, I think your scenario is fully supported with --testmon-forceselect switch (release long ago). If not let me know and let's reopen this ticket.

Hi! Yes, it works! 👍
