### ISSUE TITLE
Pytest 7.0.0 compatibility

### ISSUE THREAD

**Issue by PaddyAlton** [tarpas/pytest-testmon#174]
Hello, just a small heads up that [pytest v7.0.0](https://docs.pytest.org/en/7.0.x/changelog.html#pytest-7-0-0-2022-02-03) is now out.

[Currently pytest-testmon is restricted to pytest<7,>=5](https://github.com/tarpas/pytest-testmon/blob/master/setup.cfg#L33), leading to a dependency resolution error if one tries to use it with the latest `pytest`.

**Comment by tarpas** [comment]
Release to PYPI now. Thanks for the issue!
