### ISSUE TITLE
Using `pytest --testmon --cov` to see merged coverage results

### ISSUE THREAD

**Issue by brendanator** [tarpas/pytest-testmon#176]
When I run pytest coverage along with testmon the coverage reports only the code that was run in the selected tests.

It would be incredible if the coverage reported the merged data from the tests that are selected and the rest of the data in `.testmondata`.

I'd love to get instantly updated test converage over a whole project. Is this possible?

**Comment by tarpas** [comment]
That is not unthinkable but quite difficult. Coverage data refers to the source code by line numbers, so it becomes invalid whenever you add or remove a line. I would say it's out of scope of this project for now.

**Comment by landeholt** [comment]
Seems like commenting out this line 

https://github.com/tarpas/pytest-testmon/blob/67c80541367752cb671fb68db990011dec5de1d3/testmon/testmon_core.py#L346

doesn't seem to affect testmon, but allows coverage to keep track on the coverage data, and it looks like coverage is upserting their filenames: [coveragepy/sqldata.py](https://github.com/nedbat/coveragepy/blob/5ec587caf0bd670a0af34ad5b766119689b91b56/coverage/sqldata.py#L383-L394)

meaning that it (should) accomplish what @brendanator wished for.

**Comment by tarpas** [comment]
As I wrote: 
> Coverage data refers to the source code by line numbers, so it becomes invalid whenever you add or remove a line.

Also to have complete picture: .testmondata is a "lossy" format. Only method checksums are stored.

Testmon would have to come up with "lossless" .testmondata format which is a challenge by itself (plus keep it performant and not eating too much space)

**Comment by tarpas** [comment]
This has been implemented and release to the extent it's technically practical/feasible. The results are not perfect, see discussion here: https://github.com/tarpas/pytest-testmon/issues/86
