### ISSUE TITLE
ModuleNotFoundError: No module named 'coverage.tracer'

### ISSUE THREAD

**Issue by PerchunPak** [tarpas/pytest-testmon#180]
[Dependecies](https://github.com/PerchunPak/spiget-orm/blob/16d18a6b4758bcc4961e8c49515d0b6845689110/poetry.lock), [CI logs](https://github.com/PerchunPak/spiget-orm/runs/6101164235?check_suite_focus=true).

I also found [that usage "example"](https://github.com/nedbat/coveragepy/blob/329403bd7b3637854dd71cf1d46d084644289985/coverage/collector.py#L22).

**Comment by PerchunPak** [comment]
Only in Python 3.11

**Comment by tarpas** [comment]
Interesting. After a short investigation I realized that you probably don't have the C extensions installed (there doesn't seem to be 3.11 wheels for coverage available yet.)
you can check with `coverage --version` and it'll say `Coverage.py, version 6.3.2 without C extension`

testmon should check for this and put out better error message. Also, of course support for the PyTracer could be done. There is no ETA, please use testmon with coverage + C extension.

**Comment by PerchunPak** [comment]
I am using Github Actions for reproducing this, and I actually confused:
![image](https://user-images.githubusercontent.com/68118654/166987382-b397ba99-9235-4a97-9b86-d38188592043.png)

**Comment by tarpas** [comment]
Fixed in v 1.4.0.

**Comment by prd-quy-nguyen** [comment]
How do I fix this?

**Comment by PerchunPak** [comment]
just update to the latest version
