### ISSUE TITLE
[Question] Generate .testmondata database without running tests

### ISSUE THREAD

**Issue by Lightjohn** [tarpas/pytest-testmon#185]
Hi,

I'm trying to speed up a CI that is taking 3H30 in serial.
Testmon could do a wonderful work in that aspect (and even more).
But the first run is an issue so I thought of something:

When I create a new branch from master (against which a full CI has been run) would it be possible to just say:
here testmon generate your database against that code/commit that I know is tested and so no need to run the tests.
Generating DB should be fast and then I can develop new features and only run tests affected by my changes.

Maybe an option like `--testmon-norun` or `--testmon-updateonly`?

Is it something that could happen or did I misunderstood how testmon works?

Thanks and good job for this code!

**Comment by tarpas** [comment]
You're misunderstanding how testmon works. For a testmon run both dependency information and list of changes is needed. The process you're describing could generate the list of changes but not the dependency information. Dependencies are only determined during code execution.
