### ISSUE TITLE
python 3.11 compatibility

### ISSUE THREAD

**Issue by voidus** [tarpas/pytest-testmon#193]
This commit restricts the library to `<= 3.11`: https://github.com/tarpas/pytest-testmon/commit/1652da1e36a2c5ddf33b90892624f196d09b0cc9

Is there any reason why? I'm using poetry and have not restricted my python version to `<= 3.11`, which prevents me from installing 1.3.4. If there is an actual (expected) incompatibility, can we document that please so users can make an informed decision?

Thank you!

**Comment by tarpas** [comment]
during alpha releases of Python 3.11 it was difficult to get hold off the compiled part of coverage.py, which testmon depends on. It should be fine now for most platforms so python 3.11 is now allowed in pytest-testmon v 1.3.6
