### ISSUE TITLE
No tag for PyPI release

### ISSUE THREAD

**Issue by plannigan** [tarpas/pytest-testmon#194]
PyPI is showing a [new release](https://pypi.org/project/pytest-testmon/1.3.5/) published over the weekend. However, there is no matching tag or release on the repository.

I did a quick scan of the sdist and didn't see anything that jumped out as nefarious. Can you confirm that release is genuine and represent it in the repository?

**Comment by tarpas** [comment]
Sorry, 1.3.5 on PyPi is from me.
