### ISSUE TITLE
Feature: Prioritise affected tests, but still run changed tests

### ISSUE THREAD

**Issue by rgilton** [tarpas/pytest-testmon#197]
After making a change to my code, I'm interested in getting pytest to run the tests that are _likely to fail first_.  Particularly useful when developing in a TDD way.  I still want to run all tests so that I can be sure that everything definitely still works.

It'd be great to have an option that just prioritised running the tests that have been affected, instead of exclusively running the tests that have been affected.  Similar behaviour to pytest's existing `--ff` flag, but with testmon's knowledge of what has changed.

At the moment, my workaround is to do this: `pytest --testmon -x && pytest -x`, but obviously this suffers from having to run through collection twice etc.

**Comment by tarpas** [comment]
--testmon-noselect -x should do just that! It doesn't deselect any tests but the sorting have been made the default behaviour a couple of releases ago. Please give it a try and report back if it seems buggy!

**Comment by tarpas** [comment]
> It ddoesn't mention reordering the tests at all -- might help if it did.

Right, we'll fix that! Thanks.
