### ISSUE TITLE
Missing git version tags🤔

### ISSUE THREAD

**Issue by kloczek** [tarpas/pytest-testmon#215]
Looks laike there are no git version tags since 2.0.2.

Is it possible to add at least tag for latest 2.0.6? 🤔

**Comment by pokopt** [comment]
Hi Tomasz (@kloczek) ,
  at first thanks for feedback and using testmon.
I've added v2.0.6 tag for latest version. 
Would it be for you helpful to get every release tagged in the future?

**Comment by kloczek** [comment]
Yes it would help as my automation packaging `pytest-testmon` is using as input resource tar ball generated from git tag.
Thank you very much 👍 

Closing.
