### ISSUE TITLE
Have a command line that outputs all the tests which reach a certain line in the code

### ISSUE THREAD

**Issue by PeterKogan** [tarpas/pytest-testmon#217]
I sometimes encounter a line in one of the code functions and I'm not sure if it's covered and by which tests.

It would be great to have a command line that outputs all the tests which reach a certain line in the code.

**Comment by tarpas** [comment]
Hi, thanks for a suggestion. However, testmon doesn't store this information with line granularity. coveragepy has this functionality in the form of contexts. (And I'm not sure it's very widely used). You can change a line and run pytest --testmon and see what gets executed :). At this point I don't think it's worth adding and maintaining a functionality like this in testmon.
