### ISSUE TITLE
Change to Importlib introduces AttributeError for {d.name} if d.name does not exist. 

### ISSUE THREAD

**Issue by joshysaberastro** [tarpas/pytest-testmon#218]
![image](https://github.com/tarpas/pytest-testmon/assets/86336082/30c7ceee-34f2-4dbd-83c5-a7fa61cefbdf)

This is running on a bitbucket pipeline in a docker container with python version 3.9

**Comment by tarpas** [comment]
Thanks for reporting. I'll tackle this today.

**Comment by tarpas** [comment]
It's "hotfixed" now in 2.0.8. If you want to be on the safe side use 2.0.6, because 2.0.8 is still not very tested...
