### ISSUE TITLE
testmon.org appears to be down

### ISSUE THREAD

**Issue by ChrisCarini** [tarpas/pytest-testmon#221]
```shell
$ > date ; dig testmon.org @8.8.8.8 ; date
Sat Jul  8 14:04:59 PDT 2023

; <<>> DiG 9.10.6 <<>> testmon.org @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 10801
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;testmon.org.			IN	A

;; Query time: 1104 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Jul 08 14:05:00 PDT 2023
;; MSG SIZE  rcvd: 40

Sat Jul  8 14:05:00 PDT 2023
```

_(**Note:** My ultimate goal was to read the doc: [Determining affected tests](https://testmon.org/blog/determining-affected-tests/), but it's not available because the site appears to not be working currently.)_

**Comment by tarpas** [comment]
Thanks a lot for the notification. I had a vacation. Now it's being fixed and should propagate until tomorrow to DNS servers.

**Comment by tarpas** [comment]
It now works from most places and will propagate everywhere soon. Thanks again.

**Comment by holly-evans** [comment]
@tarpas is it down again? can't access it
