### ISSUE TITLE
Allow using --testmon-noselect and --testmon-nocollect simultaneously

### ISSUE THREAD

**Issue by GytisZ** [tarpas/pytest-testmon#227]
**Is your feature request related to a problem? Please describe.**
We're utilizing your project for local development and are keen to integrate testmon into our CI. However, we face a challenge when combining the --testmon-noselect and --testmon-nocollect flags. Using them together results in --notestmon due to [this check](https://github.com/tarpas/pytest-testmon/blob/main/testmon/configure.py#L28).

We're trying to combine them in CI in order to preserve coverage checking while also having the checks fail as fast as possible.

**Describe the solution you'd like**
Please enable the simultaneous use of both --testmon-noselect and --testmon-nocollect. This can be achieved by removing the aforementioned check.

Additionally, consider updating the documentation for --testmon-noselect on [testmon.org](https://testmon.org/). It currently omits the feature that it reorders tests.

**Describe alternatives you've considered**
An ideal solution might involve more intuitive flag naming, like splitting --testmon-noselect into two flags: --testmon-noselect and --testmon-reorder. This would clarify the purpose of each flag and reduce potential conflicts.

**Additional context**

Are there guidelines on contributing to this project? While removing the check seems straightforward, the absence of tests suggests there might be other considerations. Is there a private codebase behind [testmon.net](https://www.testmon.net/)?

**Comment by tarpas** [comment]
Thanks for suggestion. I'll still sleep on it but I think removing the check si reasonable. You're right, there is an internal codebase so yes, it's easiest I remove the line and everything else.

**Comment by GytisZ** [comment]
Thank you for considering this @tarpas . Just for additional context - noticed that there was a similar request in the comments under another issue: https://github.com/tarpas/pytest-testmon/issues/86#issuecomment-1704648525
