### ISSUE TITLE
PytestRemovedIn9Warning: The (path: py.path.local) argument is deprecated, please use (collection_path: pathlib.Path)

### ISSUE THREAD

**Issue by Anton-Aracor** [tarpas/pytest-testmon#242]
Please upgrade to the latest pytest style to avoid this bug:

```
~/.venv/lib/python3.12/site-packages/testmon/pytest_testmon.py:461: PytestRemovedIn9Warning: The (path: py.path.local) argument is deprecated, please use (collection_path: pathlib.Path)
see https://docs.pytest.org/en/latest/deprecations.html#py-path-local-arguments-for-hooks-replaced-with-pathlib-path
  def pytest_ignore_collect(self, path, config):
```

**Comment by Anton-Aracor** [comment]
@tarpas do you plan to make adjustments? Thx

**Comment by ns-rse** [comment]
@Anton-Aracor #241

**Comment by ndalchau** [comment]
This issue is a duplicate of #237 . As @ns-rse pointed out, I have an PR waiting to be approved by @tarpas that fixes it.

**Comment by ndalchau** [comment]
The PR has been merged, so I believe this issue can now be closed.

**Comment by tarpas** [comment]
I'll close it once I do a release. Sorry for the delays, busy.

**Comment by danielsiwiec** [comment]
@tarpas just checking in here - would love to see the new version released and get rid of the warnings 🙏  if there's anything I can do to help, I'm happy to!

**Comment by tarpas** [comment]
released, sorry for the delay.
