### ISSUE TITLE
Using --testmon skips --pep8 checks

### ISSUE THREAD

**Issue by blueyed** [tarpas/pytest-testmon#26]
I think that `--testmon` should be aware of tests that failed because of e.g. `--pep8` (via https://pypi.python.org/pypi/pytest-pep8).

When run without `--testmon` it results in a failure like this:

```
==== FAILURES ====
____ PEP8-check ____
…/foo.py:86:80: E501 line too long (86 > 79 characters)
    Example line that is too long ....
```

But when using `--testmon` this file/test is not being tested again.

I'm not sure if this would be possible already, but in general testmon should
reconsider any file where a test failed to be included in the next run.

/cc @RonnyPfannschmidt

**Comment by RonnyPfannschmidt** [comment]
I'm no longer working on pytest-pep8

**Comment by blueyed** [comment]
@RonnyPfannschmidt 
But can you provide some insight into if this would/should be possible?

**Comment by RonnyPfannschmidt** [comment]
No idea off hand, I suspect strange interaction between cache and the testmon plugin, but I lack deeper insights

**Comment by tarpas** [comment]
I also don't have much insight off the top of my head. testmon stores the list of failures in it's own .testmondata (so not through pytest-cache anymore). So pytest-pep8 doesn't report the failure as expected or there is a bug in testmon..

**Comment by tarpas** [comment]
I think this will be out of scope of testmon.. testmon tracks dependencies between a test and a block of python code through coverage.py 
--pep8 check is unrelated
it actually implements it's own method for "incremental" checks (only running checks on the changed files) and it will probably clash with testmon.. better to run them separately.

**Comment by tarpas** [comment]
I think this really is quite a tangled issue with limited use case.
