### ISSUE TITLE
Override pytest's exit code 5 for "no tests were run"

### ISSUE THREAD

**Issue by blueyed** [tarpas/pytest-testmon#31]
py.test will exit with code 5 in case no tests were ran (https://github.com/pytest-dev/pytest/issues/812, https://github.com/pytest-dev/pytest/issues/500#issuecomment-112204804).

I can see that this is useful in general, but with pytest-testmon this should not be an error.

Would it be possible and is it sensible to override pytest's exit code to be 0 in that case then?

My use case it using pytest-watch and its `--onfail` feature, which should not be triggered because testmon made py.test skip all tests.

**Comment by tarpas** [comment]
Yeah, I understand the use case. This would idally by done by storing the
results from previous run and returning a union of stored and new test
results (the proper exit code would be produces automatically)

**Comment by blueyed** [comment]
@tarpas 
Any update on this?
Can you provide more hints to fix this?

While pytest-watch has a patch by now that handles it, it's still an issue when running `py.test --testmon` with other tools.

**Comment by tarpas** [comment]
This is going to be implemented via #13

**Comment by tarpas** [comment]
@blueyed Do you want to take a stab on it?

**Comment by blueyed** [comment]
@tarpas 
Thanks for the offer and notification, but that's too much for me currently.
Maybe that would be a good topic for the [pytest sprint](https://pytest.org/latest/announce/sprint2016.html)!?
Also the whole topic of making this a first-class pytest plugin.
Are you coming?

**Comment by boxed** [comment]
Why is this ticket closed? I just now was hit by this and had to make a workaround...

**Comment by automaticgiant** [comment]
what was your workaround @boxed ?

**Comment by boxed** [comment]
My workaround was to make my program explicitly know about this exit code and treat it as zero if testmon is in use.

**Comment by tarpas** [comment]
This was closed because I thought #13 fixes it, sorry.

**Comment by tarpas** [comment]
Fixed in v 1.3.0.
