### ISSUE TITLE
build failure: subprocess measuring on travis-ci - python3.5

### ISSUE THREAD

**Issue by tarpas** [tarpas/pytest-testmon#36]
https://travis-ci.org/tarpas/pytest-testmon/jobs/112293175

I think the coverage_pth mechanism is not working properly on travis-ci+python35 .
Is it working locally for you? Could you have a look please? @blueyed @ktosiek

**Comment by ktosiek** [comment]
Just checked on c1e119962a410e97bfe0c80d2d407fd4d05ad607 locally and the tests passed, this must be somehow related to travis environment.

**Comment by ktosiek** [comment]
Also, we've seen a similar failure in https://github.com/tarpas/pytest-testmon/pull/29 but later commits worked (https://github.com/tarpas/pytest-testmon/pull/29#issuecomment-188443869)

**Comment by tarpas** [comment]
Tomasz, I think we never got any success with python3.5 . (e.g. see https://travis-ci.org/tarpas/pytest-testmon/pull_requests)

I disabled python3.5 on travis for now.

**Comment by ktosiek** [comment]
You can set those tests as not required, then we'll see if they ever get better: https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail

They've worked for me: https://travis-ci.org/ktosiek/pytest-testmon/builds

**Comment by tarpas** [comment]
Thanks, done.

On Mon, Feb 29, 2016 at 8:00 PM, Tomasz Kontusz <notifications@github.com>
wrote:

> You can set those tests as not required, then we'll see if they ever get
> better:
> https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail
>
> They've worked for me: https://travis-ci.org/ktosiek/pytest-testmon/builds
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarpas/pytest-testmon/issues/36#issuecomment-190334158>
> .
>



-- 
Best,
Tibor
+421907266112
-----
www.infinit.sk - The Python development team
www.testmon.org  - taking automated Python tests to a new level

**Comment by tarpas** [comment]
This seems to work now without any problem in travis.
