### ISSUE TITLE
Tests are failing on Fedora

### ISSUE THREAD

**Issue by hroncok** [tarpas/pytest-testmon#40]
I'm trying to run the test suite on Fedora 23 and I get the following failures on Python 3 and 2. Any idea what's going on?

```
=================================================== FAILURES ====================================================
______________________________ TestCoverageSubprocess.test_coverage_expected_fail _______________________________
Traceback (most recent call last):
  File ".../test/test_subprocess.py", line 29, in test_coverage_expected_fail
    assert "Couldn't read 'nonexistent_file' as a config file" in output
AssertionError: assert "Couldn't read 'nonexistent_file' as a config file" in ''
--------------------------------------------- Captured stdout call ----------------------------------------------

____________________________________ TestCoverageSubprocess.test_subprocess _____________________________________
Traceback (most recent call last):
  File ".../test/test_subprocess.py", line 43, in test_subprocess
    assert subprocess_coverage_exists, "Dir: {}".format(os.listdir(os.getcwd()))
AssertionError: Dir: ['.testmoncoveragerc', 'subprocesstest.py']
assert False
--------------------------------------------- Captured stdout call ----------------------------------------------

_______________________________________________ test_subprocesss ________________________________________________
Traceback (most recent call last):
  File ".../test/test_testmon.py", line 88, in test_subprocesss
    deps = track_it(testdir, func)
  File ".../test/test_testmon.py", line 75, in track_it
    testmon.stop_and_save(testmon_data, testdir.tmpdir.strpath, 'testnode')
  File ".../testmon/testmon_core.py", line 107, in stop_and_save
    testmon_data.set_dependencies(nodeid, self.cov.get_data(), rootdir)
  File ".../testmon/testmon_core.py", line 245, in set_dependencies
    result[filename] = checksum_coverage(self.parse_cache(filename).blocks,[1])
  File ".../testmon/testmon_core.py", line 250, in parse_cache
    self.modules_cache[module] = Module(file_name=module)
  File ".../testmon/process_code.py", line 46, in __init__
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-username/pytest-4/testdir/test_subprocesss0/testnode'
--------------------------------------------- Captured stdout call ----------------------------------------------
running ['/usr/bin/python3', '/usr/lib/python3.4/site-packages/pytest.py', '--basetemp=/tmp/pytest-username/pytest-4/testdir/test_subprocesss0/runpytest-0', 'test_a.py'] curdir= /tmp/pytest-username/pytest-4/testdir/test_subprocesss0

```

```
=================================================== FAILURES ====================================================
______________________________ TestCoverageSubprocess.test_coverage_expected_fail _______________________________
Traceback (most recent call last):
  File ".../test/test_subprocess.py", line 29, in test_coverage_expected_fail
    assert "Couldn't read 'nonexistent_file' as a config file" in output
AssertionError: assert "Couldn't read 'nonexistent_file' as a config file" in ''
--------------------------------------------- Captured stdout call ----------------------------------------------

____________________________________ TestCoverageSubprocess.test_subprocess _____________________________________
Traceback (most recent call last):
  File ".../test/test_subprocess.py", line 43, in test_subprocess
    assert subprocess_coverage_exists, "Dir: {}".format(os.listdir(os.getcwd()))
AssertionError: Dir: ['.testmoncoveragerc', 'subprocesstest.py']
assert False
--------------------------------------------- Captured stdout call ----------------------------------------------

_______________________________________________ test_subprocesss ________________________________________________
Traceback (most recent call last):
  File ".../test/test_testmon.py", line 88, in test_subprocesss
    deps = track_it(testdir, func)
  File ".../test/test_testmon.py", line 75, in track_it
    testmon.stop_and_save(testmon_data, testdir.tmpdir.strpath, 'testnode')
  File ".../testmon/testmon_core.py", line 107, in stop_and_save
    testmon_data.set_dependencies(nodeid, self.cov.get_data(), rootdir)
  File ".../testmon/testmon_core.py", line 245, in set_dependencies
    result[filename] = checksum_coverage(self.parse_cache(filename).blocks,[1])
  File ".../testmon/testmon_core.py", line 250, in parse_cache
    self.modules_cache[module] = Module(file_name=module)
  File ".../testmon/process_code.py", line 46, in __init__
    with open(file_name) as f:
IOError: [Errno 2] No such file or directory: '/tmp/pytest-username/pytest-5/testdir/test_subprocesss0/testnode'
--------------------------------------------- Captured stdout call ----------------------------------------------
running ['/usr/bin/python2', '/usr/lib/python2.7/site-packages/pytest.py', '--basetemp=/tmp/pytest-username/pytest-5/testdir/test_subprocesss0/runpytest-0', 'test_a.py'] curdir= /tmp/pytest-username/pytest-5/testdir/test_subprocesss0

```

Thank You.

**Comment by tarpas** [comment]
https://pypi.python.org/pypi/coverage_pth is not installing properly. I
know it's causing problems on some linux distributions.

You're not getting the coverage_pth.pth created at the right place or at
all.

coverage_pth is a hassle, that's why it's not a hard dependency...

Ideally this problem should be solved by coverage.py, so I'm not sure how
to proceed. Could you experiment with coverage_pth yourself?
ᐧ

On Fri, Mar 11, 2016 at 10:48 PM, Miro Hrončok <notifications@github.com>
wrote:

> I'm trying to run the test suite on Fedora 23 and I get the following
> failures on Python 3 and 2. Any idea what's going on?
>
> =================================================== FAILURES ====================================================
> ______________________________ TestCoverageSubprocess.test_coverage_expected_fail _______________________________
> Traceback (most recent call last):
>   File ".../test/test_subprocess.py", line 29, in test_coverage_expected_fail
>     assert "Couldn't read 'nonexistent_file' as a config file" in output
> AssertionError: assert "Couldn't read 'nonexistent_file' as a config file" in ''
> --------------------------------------------- Captured stdout call ----------------------------------------------
>
> ____________________________________ TestCoverageSubprocess.test_subprocess _____________________________________
> Traceback (most recent call last):
>   File ".../test/test_subprocess.py", line 43, in test_subprocess
>     assert subprocess_coverage_exists, "Dir: {}".format(os.listdir(os.getcwd()))
> AssertionError: Dir: ['.testmoncoveragerc', 'subprocesstest.py']
> assert False
> --------------------------------------------- Captured stdout call ----------------------------------------------
>
> _______________________________________________ test_subprocesss ________________________________________________
> Traceback (most recent call last):
>   File ".../test/test_testmon.py", line 88, in test_subprocesss
>     deps = track_it(testdir, func)
>   File ".../test/test_testmon.py", line 75, in track_it
>     testmon.stop_and_save(testmon_data, testdir.tmpdir.strpath, 'testnode')
>   File ".../testmon/testmon_core.py", line 107, in stop_and_save
>     testmon_data.set_dependencies(nodeid, self.cov.get_data(), rootdir)
>   File ".../testmon/testmon_core.py", line 245, in set_dependencies
>     result[filename] = checksum_coverage(self.parse_cache(filename).blocks,[1])
>   File ".../testmon/testmon_core.py", line 250, in parse_cache
>     self.modules_cache[module] = Module(file_name=module)
>   File ".../testmon/process_code.py", line 46, in __init__
>     with open(file_name) as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-username/pytest-4/testdir/test_subprocesss0/testnode'
> --------------------------------------------- Captured stdout call ----------------------------------------------
> running ['/usr/bin/python3', '/usr/lib/python3.4/site-packages/pytest.py', '--basetemp=/tmp/pytest-username/pytest-4/testdir/test_subprocesss0/runpytest-0', 'test_a.py'] curdir= /tmp/pytest-username/pytest-4/testdir/test_subprocesss0
>
>
> =================================================== FAILURES ====================================================
> ______________________________ TestCoverageSubprocess.test_coverage_expected_fail _______________________________
> Traceback (most recent call last):
>   File ".../test/test_subprocess.py", line 29, in test_coverage_expected_fail
>     assert "Couldn't read 'nonexistent_file' as a config file" in output
> AssertionError: assert "Couldn't read 'nonexistent_file' as a config file" in ''
> --------------------------------------------- Captured stdout call ----------------------------------------------
>
> ____________________________________ TestCoverageSubprocess.test_subprocess _____________________________________
> Traceback (most recent call last):
>   File ".../test/test_subprocess.py", line 43, in test_subprocess
>     assert subprocess_coverage_exists, "Dir: {}".format(os.listdir(os.getcwd()))
> AssertionError: Dir: ['.testmoncoveragerc', 'subprocesstest.py']
> assert False
> --------------------------------------------- Captured stdout call ----------------------------------------------
>
> _______________________________________________ test_subprocesss ________________________________________________
> Traceback (most recent call last):
>   File ".../test/test_testmon.py", line 88, in test_subprocesss
>     deps = track_it(testdir, func)
>   File ".../test/test_testmon.py", line 75, in track_it
>     testmon.stop_and_save(testmon_data, testdir.tmpdir.strpath, 'testnode')
>   File ".../testmon/testmon_core.py", line 107, in stop_and_save
>     testmon_data.set_dependencies(nodeid, self.cov.get_data(), rootdir)
>   File ".../testmon/testmon_core.py", line 245, in set_dependencies
>     result[filename] = checksum_coverage(self.parse_cache(filename).blocks,[1])
>   File ".../testmon/testmon_core.py", line 250, in parse_cache
>     self.modules_cache[module] = Module(file_name=module)
>   File ".../testmon/process_code.py", line 46, in __init__
>     with open(file_name) as f:
> IOError: [Errno 2] No such file or directory: '/tmp/pytest-username/pytest-5/testdir/test_subprocesss0/testnode'
> --------------------------------------------- Captured stdout call ----------------------------------------------
> running ['/usr/bin/python2', '/usr/lib/python2.7/site-packages/pytest.py', '--basetemp=/tmp/pytest-username/pytest-5/testdir/test_subprocesss0/runpytest-0', 'test_a.py'] curdir= /tmp/pytest-username/pytest-5/testdir/test_subprocesss0
>
>
> Thank You.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarpas/pytest-testmon/issues/40>.
>



-- 
Best,
Tibor
+421907266112
-----
www.infinit.sk - The Python development team
www.testmon.org  - taking automated Python tests to a new level

**Comment by hroncok** [comment]
When I get that file, the tests pass, but the PyPI package has no license information what so ever, so i cannot package it to Fedora. Is this only needed for testmon's tests, or also on runtime?

**Comment by tarpas** [comment]
It's also for runtime. (for test suites for subprocesses)
This doesn't do? 
https://github.com/dougn/coverage_pth/blob/master/LICENSE.txt
