### ISSUE TITLE
Issue with pytest-sugar

### ISSUE THREAD

**Issue by marctc** [tarpas/pytest-testmon#41]
Hi,
When I try to use pytest-testmon with [pytest-sugar](https://github.com/Frozenball/pytest-sugar) it throws me this error:

```
pytest_sugar.py:71: in pytest_deselected
    pluginmanager = items[0].config.pluginmanager
 AttributeError: 'str' object has no attribute 'config
```
I know that this issue happens on pytest-sugar plugin but maybe you are able to figure out where the problem is.

**Comment by tarpas** [comment]
Are you using the newest pytest-testmon version? I think this was fixed
recently.
ᐧ

On Wed, Mar 16, 2016 at 4:48 PM, Marc Tudurí <notifications@github.com>
wrote:

> Hi,
> When I try to use pytest-testmon with pytest-sugar
> <https://github.com/Frozenball/pytest-sugar> it throws me this error:
>
> pytest_sugar.py:71: in pytest_deselected
>     pluginmanager = items[0].config.pluginmanager
>  AttributeError: 'str' object has no attribute 'config
>
> I know that this issue happens on pytest-sugar plugin but maybe you are
> able to figure out where the problem is.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tarpas/pytest-testmon/issues/41>
>



-- 
Best,
Tibor
+421907266112
-----
www.infinit.sk - The Python development team
www.testmon.org  - taking automated Python tests to a new level

**Comment by marctc** [comment]
Yikes, I didn't realized that you release a new version. Yes, it works. Thanks!
