### ISSUE TITLE
compatibility with pytest 3.0.2

### ISSUE THREAD

**Issue by heloisem** [tarpas/pytest-testmon#48]
Hi, 
I am new in Python and I am interested in implementing testmon in my circleci builds. 
The problem is I need pytest 3.0.2 to run my tests, and when installing testmon it automatically uninstalls my pytest version to install pytest 2.9.2 which causes my circle builds to fail. 
Any idea what can I do ?
Thanks in advance

**Comment by heloisem** [comment]
Okay, just noticed you made a commit about it here:

**Comment by blueyed** [comment]
@tarpas hopefully does it soon.

As for now: can you confirm that current master works for you?

**Comment by heloisem** [comment]
Yes it works well thank you !

**Comment by tarpas** [comment]
testmon with pytest 3.0.x support, released to PYPI
