### ISSUE TITLE
Specyfing some code depends on a data file

### ISSUE THREAD

**Issue by ktosiek** [tarpas/pytest-testmon#49]
Use case I'm struggling with: .sql with SQL views, that don't trigger test reruns.

Is it possible to specify that some function/class should be considered changed when a specific file changes? I'd like to invalidate everything that uses a specific ORM class that maps to a SQL view when I'm changing that view.

**Comment by ktosiek** [comment]
Hmm, that won't work, as there's no code that is specific to using specific view. So I'd need some way to inject my own usage/changes information.

**Comment by tarpas** [comment]
https://github.com/tarpas/pytest-testmon/issues/12
