### ISSUE TITLE
Might deselect too much after interrupt

### ISSUE THREAD

**Issue by blueyed** [tarpas/pytest-testmon#50]
I've just seen that testmon deselect all items, after I've canceled the test run using KeyboardInterrupt.

I am using pytest-sugar also, and it was at 9% at that time.

```
Test session starts (platform: linux, Python 3.5.2, pytest 3.0.3, pytest-sugar 0.7.1)
cachedir: .cache
Django settings: velodrome.settings (from environment variable)
testmon=True, changed files: 17, skipping collection of 0 items, run variant: 60332d2767d943a82bceab2bffc7c6ea
…
^C
```

The next run deselected all items then:
```
      Test session starts (platform: linux, Python 3.5.2, pytest 3.0.3, pytest-sugar 0.7.1)
cachedir: .cache
Django settings: velodrome.settings (from environment variable)
testmon=True, changed files: 0, skipping collection of X items, run variant: 60332d2767d943a82bceab2bffc7c6ea
rootdir: …
plugins: xdist-1.15.dev9+ngba35a3d, catchlog-1.2.2, notifier-0.3, incremental-0.4.2, instafail-0.3.0, sugar-0.7.1, testmon-0.8.3, django-3.0.1.dev3+ngf18a858, random-0.2, asyncio-0.5.0, repeat-0.4.1, cov-2.4.0, mock-1.2, profiling-1.1.1, pdb-0.1.0, pylama-7.1.0, bpdb-0.1.4

==================================================== X tests deselected =====================================================

Results (0.14s):
     X deselected
```

I fear that this might be caused by https://github.com/tarpas/pytest-testmon/pull/47/commits/f53d87918190a16a38966696357b6d6994e3e851 (or something else from the PR (#47)).

**Comment by tarpas** [comment]
I agree the PR #47 is a suspect but I didn't find out why, even after some exploration and thinking about it. It shouldn't be too difficult to write a unit test for it, so that would be a next step. Or should we revert the PR? How much do you need the feature?

**Comment by blueyed** [comment]
> How much do you need the feature?

Not more than being on the save side of not ignoring too much.. ;)
So feel free to revert it for now, but I agree that a test for this would be the best - from there it would be easy to bisect.

**Comment by tarpas** [comment]
https://github.com/tarpas/pytest-testmon/tree/refactor addresses saving intermediate design. We'll definitely revert the PR https://github.com/tarpas/pytest-testmon/pull/47 stuff . And see.
