### ISSUE TITLE
Absolute paths in values :(

### ISSUE THREAD

**Issue by boxed** [tarpas/pytest-testmon#52]
```
>>> from testmon.testmon_core import *
>>> t = TestmonData('.')
>>> t.init_connection()
>>> t.read_data()
>>> t.node_data.keys()[0]
u'project/unittest/test_foo.py::test_foo'
>>> t.node_data.values()[0].keys()[0]
u'/data/bamboo/bamboo-agent-home/xml-data/build-dir/XXX/foo/bar/__init__.py'
```

The node_data keys are relative paths, but the node_data data is absolute paths. It would be great if they were both relative. 

My use case: 

We have a big and slow test suite that is unpractical to rerun on all developers machines all the time. So we've got the CI environment to create the testmon database periodically and a little script to download this cache unto local developers machines so running testmon is super fast and nice.

I'm going to try to work around the problem right now by going through the entire dataset and changing the paths, but it would be nice if the paths were relative from the beginning so I didn't have to.

**Comment by tarpas** [comment]
https://github.com/tarpas/pytest-testmon/commit/f533c2a8d922248e80de769bef8efdfd011e88d3 addresses this issue
