### ISSUE TITLE
Stored results not adjusted for different options (verbose, tbstyle)

### ISSUE THREAD

**Issue by blueyed** [tarpas/pytest-testmon#57]
Even though I am passing in `-vv` I get the message `Use -v to get the full diff` with the AssertionError on failed tests:

```
___ test_foo ___
project/app/tests/test_foo.py:175: in test_foo
    assert new == [
E   assert [{'asset': ..._name': None}] == [{'asset': '..._name': None}]
E     At index 2 diff: {'asset_name': None, 'asset': None} != {'asset_name': None, 'asset': 'INVALID-UUID'}
E     Use -v to get the full diff
!!! 2 errors during collection !!!
```

**Comment by tarpas** [comment]
I don't understand. testmon stores the failure's longrepr. If the test is not re-executed, than it's re-reported with exact same report as stored. Are you hitting this design flaw?

If not, please report exactly what you do and what you expect.

**Comment by blueyed** [comment]
Yes, that appears to explain it: I get a failure, then try to run it with `-vv`, where it is not executed again.

So it should be stored together with the arguments being used, at least some of them.. also other plugins, like pytest-sugar and pytest-instafail etc might have influence on the outcome.

**Comment by blueyed** [comment]
Reporting is improved in https://github.com/tarpas/pytest-testmon/pull/138.

**Comment by tarpas** [comment]
This has been fixed longer ago, with re-executing failures.
