### ISSUE TITLE
testmon can't be loaded in pytest 3.1

### ISSUE THREAD

**Issue by saily** [tarpas/pytest-testmon#65]
testmon does not work with pytest 3.1, what's missing to make testmon pytest 3.1 compatible? Currently the plugin cannot be loaded on test execution.

    _pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'testmon' could not be loaded:
     (pytest 3.1.0 (/.../lib/python3.4/site-packages), Requirement.parse('pytest<3.1,>=2.8.0'))!

**Comment by blueyed** [comment]
See https://github.com/tarpas/pytest-testmon/pull/64.

**Comment by saily** [comment]
@blueyed thanks. i could not find an issue, so we should leave this open to inform others.

**Comment by saily** [comment]
Closed by merging #64
