### ISSUE TITLE
-k expression is ignored when not using --tlf

### ISSUE THREAD

**Issue by blueyed** [tarpas/pytest-testmon#73]
`pytest --testmon -k foo` should  only consider tests matching "foo", but it will display the recorded result for all failed tests?!
Only when used with `--tlf` `-k` seems to be respected.

**Comment by blueyed** [comment]
That might only affect collection..

**Comment by blueyed** [comment]
This is because `pytest_ignore_collect` ignores the whole file already, and then pytest's filtering (`-k`) is not applied.

**Comment by blueyed** [comment]
Fixed in https://github.com/tarpas/pytest-testmon/pull/134.

**Comment by jacksongoode** [comment]
@blueyed Is this fixed? `testmon` deactivates when `-k` is passed.

**Comment by tarpas** [comment]
this tickets refers to testmon version long ago, so it's not a great pleace to discuss current behavior or cli options.

@jacksongoode --testmon-forceselect doesn't disable writing to .testmondata and it should cover most use cases. 
As for coverage depends on what you mean. If you still have question, please test yourself or explain.
