### ISSUE TITLE
Changing conftest reruns all tests

### ISSUE THREAD

**Issue by blueyed** [tarpas/pytest-testmon#74]
Even with a test file that does not use any fixtures (beside autouse ones), changes to `conftest.py` (e.g. adding a function, which is not a fixture) seem to retrigger all tests to be run.

`pytest --fixtures-per-test` shows that there are some autouse ones, but those are not changed:

```
…
django_db_blocker
…
django_test_environment
…
```

`test_mon.py`:
```python
def test_testmon():
    assert 1
```

Is this expected?
I've found https://github.com/tarpas/pytest-testmon/commit/ccc4088156cb816fe1be17834db7b7fa58a93ab8 (#17), which seems to be related.
I've not tried it in a minimal project.

**Comment by tarpas** [comment]
Adding a function changes the base block of the file, so it's definitelly expected. Opposed to that changing something withing a function which is never called is expected not to trigger re-execution but that's not your case, right?

**Comment by blueyed** [comment]
Yes, it seems to be the case here.
Can this be avoided though somehow?

**Comment by tarpas** [comment]
No sorry, it's a direct consequence of "the lines which are executed can have so many side effects that we don't try to determine their real dependencies, we re-execute dependent tests even on smallest change" https://github.com/tarpas/pytest-testmon/wiki/Determining-affected-tests
