### ISSUE TITLE
sqlite3.OperationalError: database is locked in _check_data_version

### ISSUE THREAD

**Issue by tarpas** [tarpas/pytest-testmon#75]
This is copied from #68: I found a similar issue when running with xdist. Since 0.9.5 I get the "database is locked" error when it is writing the stored_data_version, when executing _check_data_version() from init_connection(). Downgrading to 0.9.4 works fine.

**Comment by tarpas** [comment]
@maestro-brentpanther Could you please copy and paste your stack trace here? Thanks!

**Comment by tarpas** [comment]
This issue is addressed in branch https://github.com/tarpas/pytest-testmon/tree/no_sqlite_lock . @maestro-brentpanther Could you test it?

**Comment by maestro-brentpanther** [comment]
@tarpas Yes, this does resolve the issue for me, thanks.
