### ISSUE TITLE
Distribution package improvements

### ISSUE THREAD

**Issue by webknjaz** [tarpas/pytest-testmon#85]
Hi @tarpas,

I've noticed you're doing lots of manual changes during publishing the new version. Would you be interested in doing certain improvements? I'm willing to invest some time in such contribution if approved.

* [ ] automatic version calculation from git tag (via setuptools-scm and its extensions, added via `setup_requires=`)
* [ ] automatic deployment of git-tagged versions to PYPI from Travis CI
* [ ] deployment of binary wheel (a single universal wheel should be enough, because you don't rely on C-extensions)

**Comment by tarpas** [comment]
It's done like that on cheroot? I'll have a look. But for me it's actually very quick "feel good" ritual.

**Comment by webknjaz** [comment]
@tarpas yes, but `.travis.yaml` is far more complicated than you need here in cheroot.

**Comment by tarpas** [comment]
not on the "roadmap" in the near future, but thanks for suggestion.
