### ISSUE TITLE
--testmon -x runs a test always, although there is a failing one already

### ISSUE THREAD

**Issue by blueyed** [tarpas/pytest-testmon#90]
Using `-x` with `--testmon` will still run a single test each time.

First run, where the first test fails:
```
% rm .testmondata
% pytest --testmon -p no:randomly -x project/app/tests/test_api_users.py 
===== test session starts =====
platform linux -- Python 3.6.4, pytest-3.4.1, py-1.5.2, pluggy-0.6.0
Django settings: project.settings (from environment variable)
testmon=True, changed files: 0, skipping collection of 0 items, run variant: f7f570e59cc3ddf4715a2c25785a61d1
rootdir: …/project/project, inifile: setup.cfg
plugins: xdist-1.22.1, travis-fold-1.3.0, testmon-0.9.9, repeat-0.4.1, profiling-1.2.11, mock-1.7.0, forked-0.2, django-3.1.2, cov-2.5.1, asyncio-0.8.0, annotate-1.0.1, celery-4.1.0, pdb-0.3.0.dev0
collected 108 items                                                                                                                                                                          

project/app/tests/test_api_users.py F
===== short test summary info =====
FAIL project/app/tests/test_api_users.py::test_foo

===== FAILURES =====
…
===== 1 failed in 3.06 seconds =====
```

Second run:
```
% pytest --testmon -p no:randomly -x project/app/tests/test_api_users.py
===== test session starts =====
…
testmon=True, changed files: 0, skipping collection of 1 items, run variant: f7f570e59cc3ddf4715a2c25785a61d1
…
collected 108 items                                                                                                                                                                          

project/app/tests/test_api_users.py F.
===== short test summary info =====
FAIL project/app/tests/test_api_users.py::test_foo

…
===== 1 failed, 1 passed, 1 deselected in 3.06 seconds =====
```

Third run:
```
% pytest --testmon -p no:randomly -x project/app/tests/test_api_users.py
…
testmon=True, changed files: 0, skipping collection of 2 items, run variant: f7f570e59cc3ddf4715a2c25785a61d1
…
collected 108 items                                                                                                                                                                          

project/app/tests/test_api_users.py F.
===== short test summary info =====
FAIL project/app/tests/test_api_users.py::test_foo
…
===== 1 failed, 1 passed, 2 deselected in 3.02 seconds =====
```

When using `-vv` which triggers pytest's progress display it can be seen that with the first (not re-run) test "100%" is reported, and then "1%" with the test that gets run:

```
% pytest --testmon -vv -p no:randomly -x project/app/tests/test_api_users.py 
…
testmon=True, changed files: 0, skipping collection of 3 items, run variant: f7f570e59cc3ddf4715a2c25785a61d1
…
collected 108 items                                                                                                                                                                          

project/app/tests/test_api_users.py::test_foo FAILED   [100%]
project/app/tests/test_api_users.py::test_bar PASSED   [  1%]
…
===== 1 failed, 1 passed, 3 deselected in 3.99 seconds =====
```

I think testmon should not run any test when `-x` is used and it knows about a failing test already.

**Comment by tarpas** [comment]
You're right Daniel. I'm quite unhappy with the implementation of the --tlf option. I've tried to fix this and other issues recently but the code is ripe for big improvement.

**Comment by tarpas** [comment]
@blueyed d9083c4 has a lot of changes, including the processing of failed tests. I suspect it's still not correct, but it would help if you could test other aspects. (without -x)

**Comment by max-imlian** [comment]
FYI I'm still having real issues with `testmon`, where it doesn't run tests despite both changes in the code and existing failures, even when I pass `--tlf`.

I love the goals of `testmon`, and it's performs _so_ well in 90% of cases that it's become an essential part of my workflow. As a result, when it ignores tests that have changed, it's frustrating. I've found that `--tlf` often doesn't work, which is a shame as it was often a 'last resort' to `testmon` making a mistake in ignoring too many tests.

Is there any info I can supply that would help debug this? I'm happy to post anything.

Would there be any use of a 'Conservative' mode, where `testmon` would lean towards testing too much? A Type I error is far less costly than a Type II.

**Comment by blueyed** [comment]
@max-imlian 
I think you should create a new issue - there is nothing about `-x` in your case (and I would have to revisit this issue (as the original reporter) myself).

I share your feelings though, and therefore it would be good to have a separate issue with a reproducible test case at best.
FWIW, `--tlf` usually works for me - it would be interesting to see the raw output from `pytest -vv --tlf` when it fails for you - in a new issue at best.

**Comment by tarpas** [comment]
--testmon -x is not easy to fix, because -x and --testmon both try to manipulate the set of executed tests in a different way. 

Possible solutions:
1. --testmon-x switch but that's not nice nor user friendly
2. --testmon would detect -x and remove it from the running config but use it internally to do the right thing
3. testmon would add custom, interactive marks for each test which would have value of either "stale"/"current" and they could be used in -m expressions . In this way the advanced user could actually select any tests they like through complex expressions.

**Comment by blueyed** [comment]
> --testmon -x is not easy to fix, because -x and --testmon both try to manipulate the set of executed tests in a different way.

`-x` does not manipulate the set of executed tests, it is just that testmon reports failed items in the beginning already.

A fix for this would be reporting failed items at the end only.

**Comment by blueyed** [comment]
Fixed in https://github.com/tarpas/pytest-testmon/pull/134.
