### ISSUE TITLE
make new history database without running test

### ISSUE THREAD

**Issue by henningphan** [tarpas/pytest-testmon#94]
Hello,
Im restricted with a convoluted setup with slow test yada yada.

It would be nice to have no .testmondata, from there create the database for all tests, without running the tests. And from that point on I want to standard behaviour of testmon, that is to run tests which are affected by modified files.

Im looking into how to do this myself, but I could need some guidance in the pytest workflow. Where it collects tests, ignores them, how to calculate dependencies to tests and save it to the db.

**Comment by tarpas** [comment]
I am not sure I understand. It's no possible to create the database without running the tests, because the dynamic coverage data is essential.

**Comment by henningphan** [comment]
To clarify my scenario:
1. Assume there is no .testmondata.
2. I want to run pytest --testmon --checkpoint which creates .testmondata without running any tests.
3. Running pytest --testmon should run no tests because no files have been changed since point 2.
4. Edit some files that affect a test.
5. Run pytest --testmon should run 1 test because of point 4.

Would this be possible?

**Comment by tarpas** [comment]
No, 4. wouldn't know which files affect a test, without 2. actually running the tests.

**Comment by henningphan** [comment]
Thank you, I been spending too many hours trying to solve this.
